### Default metric value to identity a idle resource
### DO NOT CHANGE THIS FILE, refer to config.yaml for modification below metrics.



resources:
    EBS:
      unused: 0    #submission of DiskWriteOps and DiskReadOps
      cloudwatch_metrics_days: 14
      cloudwatch_metrics_period: 1209600
    
    EC2:
      avgCpu: 1
      maxCpu: 1
      netInOut: 5000
      cloudwatch_metrics_days: 14
      cloudwatch_metrics_period: 1209600
    
    ELASTICSEARCH:
      sumCacheHitMiss: 0 #Submission of Cache Hit and Miss
      cloudwatch_metrics_days: 14
      cloudwatch_metrics_period: 1209600

    ELASTICACHE:
      sumCacheHitMiss: 0 #Submission of Cache Hit and Miss
      cloudwatch_metrics_days: 14
      cloudwatch_metrics_period: 1209600
      
    LB:
      connectionCount: 1 
      cloudwatch_metrics_days: 14
      cloudwatch_metrics_period: 1209600
    
    RDS:
      connectionCount: 0
      cloudwatch_metrics_days: 14
      cloudwatch_metrics_period: 1209600
    
    REDSHIFT:
      dbConnectionCount: 0
      cloudwatch_metrics_days: 14
      cloudwatch_metrics_period: 1209600
    
config:
  env:
    channel_name: 'test-report'             #Slack Channel Name
    slack_token: '-'                   #Slack Channel Token
    config: 'Null'                         #Configuration for Cloudwatch e.g. ebs=20, lb=15
    from_address: '-'                #SES verified email address from which email is to be sent
    to_address: '-'         #Email addresses of recipents (Comma Separated)
    ses_region: '-'                    #Region where SES is configured
    reporting_platform: 'slack'    #Email/Slack/Email and Slack
    account_name: 'AWS Account'
    webhook_url: 'https://hooks.slack.com/services/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'
    
